# Generated by Django 5.2.8 on 2025-11-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_name_alter_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
